### ISSUE TITLE
Clojure version upgrade breaks the katas

### ISSUE THREAD

**Issue by AlexVPopov** [chefy-io/clojure-katas#9]
Hello,

Since the the upgrade to Clojure 1.10 the `katas-run` and `katas-answers` commands are broken. On `master`, when running `lein katas-run`, I get:

```bash
Exception in thread "main" Syntax error macroexpanding core/defproblem at (clojure_katas/sine_angle.clj:4:1).
Unimplemented problem
	at clojure.lang.Compiler.macroexpand1(Compiler.java:7009)
	at clojure.lang.Compiler.macroexpand(Compiler.java:7074)
	at clojure.lang.Compiler.eval(Compiler.java:7160)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$use.invokeStatic(core.clj:6093)
	at clojure.core$use.doInvoke(core.clj:6093)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure_katas.sine_angle_test$eval177$loading__6706__auto____178.invoke(sine_angle_test.clj:1)
	at clojure_katas.sine_angle_test$eval177.invokeStatic(sine_angle_test.clj:1)
	at clojure_katas.sine_angle_test$eval177.invoke(sine_angle_test.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure_katas.test_runner$run_tests$fn__168.invoke(test_runner.clj:27)
	at clojure_katas.test_runner$run_tests.invokeStatic(test_runner.clj:26)
	at clojure_katas.test_runner$run_tests.invoke(test_runner.clj:21)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init9063866589446978454.clj:1)
	at user$eval140.invoke(form-init9063866589446978454.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Unimplemented problem {:symbol clojure-katas.sine-angle/sine}
	at clojure_katas.core$defproblem.invokeStatic(core.clj:8)
	at clojure_katas.core$defproblem.doInvoke(core.clj:4)
	at clojure.lang.RestFn.invoke(RestFn.java:500)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6992)
	... 74 more
Error encountered performing task 'run' with profile(s): 'test'
Suppressed exit
```

and when running `lein katas-answers` I get:

```bash
Testing clojure-katas.sine-angle-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.arranged-prob-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.exponential-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.nth-fibonacci-test

Ran 2 tests containing 14 assertions.
0 failures, 0 errors.

Testing clojure-katas.greatest-common-divisor-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.reverse-binary-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.max-prime-factor-test

Ran 1 tests containing 4 assertions.
0 failures, 0 errors.

Testing clojure-katas.pascal-triangle-test

Ran 2 tests containing 4 assertions.
0 failures, 0 errors.

Testing clojure-katas.count-coin-change-test

Ran 2 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.procedural-sum-test

Ran 2 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.square-root-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.

Testing clojure-katas.integral-test

Ran 1 tests containing 2 assertions.
0 failures, 0 errors.
Exception in thread "main" Syntax error compiling at (clojure/contrib/math.clj:46:1).
	at clojure.lang.Compiler.analyze(Compiler.java:6808)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:3103)
	at clojure.lang.Compiler.analyze(Compiler.java:6797)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1020)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6120)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5467)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4029)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7104)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.eval(Compiler.java:7173)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure_katas.fixed_point$eval660$loading__6706__auto____661.invoke(fixed_point.clj:1)
	at clojure_katas.fixed_point$eval660.invokeStatic(fixed_point.clj:1)
	at clojure_katas.fixed_point$eval660.invoke(fixed_point.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$use.invokeStatic(core.clj:6093)
	at clojure.core$use.doInvoke(core.clj:6093)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure_katas.fixed_point_test$eval654$loading__6706__auto____655.invoke(fixed_point_test.clj:1)
	at clojure_katas.fixed_point_test$eval654.invokeStatic(fixed_point_test.clj:1)
	at clojure_katas.fixed_point_test$eval654.invoke(fixed_point_test.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure_katas.test_runner$run_tests$fn__168.invoke(test_runner.clj:27)
	at clojure_katas.test_runner$run_tests.invokeStatic(test_runner.clj:26)
	at clojure_katas.test_runner$run_tests.invoke(test_runner.clj:21)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval140.invokeStatic(form-init1531134031240191782.clj:1)
	at user$eval140.invoke(form-init1531134031240191782.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: remainder in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7413)
	at clojure.lang.Compiler.resolve(Compiler.java:7357)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7318)
	at clojure.lang.Compiler.analyze(Compiler.java:6768)
	... 115 more
Error encountered performing task 'run' with profile(s): 'test,answers'
Suppressed exit
```

I'm willing to provide a solution, however I'm new to Clojure and am not sure what the problem is. Alternatively, we could rollback the version upgrade until a proper PR for a version upgrade is submitted?

**Comment by marshallshen** [comment]
@AlexVPopov this issue has been resolved, can you follow the updated README and let me know if you still encounter issues? Thank you for the feedback!
